name: geog-py
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - dav1d=1.2.1
  - freexl=2.0.0
  - gdal=3.10.0
  - geos=3.13.0
  - geotiff=1.7.3
  - giflib=5.2.2
  - icu=75.1
  - json-c=0.18
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif16=1.1.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.11.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgdal-core=3.10.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libheif=1.19.5
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libpng=1.6.44
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - minizip=4.0.7
  - ncurses=6.5
  - numpy=2.2.1
  - openssl=3.4.0
  - pcre2=10.44
  - pip=24.3.1
  - proj=9.5.1
  - python=3.12.8
  - python_abi=3.12
  - rav1e=0.6.6
  - readline=8.2
  - setuptools=75.6.0
  - snappy=1.2.1
  - sqlite=3.47.2
  - svt-av1=2.3.0
  - tk=8.6.13
  - uriparser=0.9.8
  - wheel=0.45.1
  - x265=3.5
  - xerces-c=3.2.5
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - zlib=1.3.1
  - zstd=1.5.6
